vich_uploader:
    db_driver: orm

    mappings:
       nftImages:
           uri_prefix: /images/nftImages
           upload_destination: '%kernel.project_dir%/public/images/nftImages'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
       userImages:
           uri_prefix: /images/userImages
           upload_destination: '%kernel.project_dir%/public/images/userImages'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
