controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

root:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /api
        permanent: true
